### ISSUE TITLE
Makefile excluded from npm

### ISSUE THREAD

**Issue by thejameskyle** [6to5/6to5#359]
Since we tell people to build the library with `make build` it _makes_ sense to include the Makefile on npm. make make make

**Comment by sebmck** [comment]
It'll blow up because the npm install doesn't include a lot of files for caching, size, and performance reasons. All the files that you can possibly get via `make build` are available in the npm releases anyway. This has come up before and if you want to do anything developmenty with 6to5 then you have to do it via git.
