### ISSUE TITLE
Generators aren't blacklisted in 6to5/register if the current environment supports them

### ISSUE THREAD

**Issue by vdemedes** [6to5/6to5#372]
Seems like ES6 features, like generators don't get detected as already implemented natively. I am using Node.js v0.11.14, which has support for generators with `--harmony` option, but 6to5 does not see that and replaces native generator functions with regenerator ones.

**Comment by sebmck** [comment]
I assume you're referring to `6to5/register` and/or `6to5-node`? This is because [regenerator](https://github.com/facebook/regenerator) transforms both [async functions](https://github.com/jhusain/asyncgenerator) and normal generators. I've opened an issue facebook/regenerator#161 which when resolved will allow 6to5 to blacklist `generators` without support for async functions. See [register.js](https://github.com/6to5/6to5/blob/master/lib/6to5/register.js#L41-65) for all the current blacklist tests.

**Comment by vdemedes** [comment]
I am referring to `6to5/register`, haven't used `6to5-node` much. My Node.js version supports generators natively, but 6to5 replaces them with regenerator functions. If I am using `blacklist: ['generators']`, everything is correct and 6to5 skips my generator functions and does not transform them. But the thing is, it does not detect that generators are supported natively.

**Comment by sebmck** [comment]
As I said before, the `generators` transformers tests both generators **and** async functions, so in order to blacklist it both features need to be supported. Until facebook/regenerator#161 is resolved there's nothing I can do about it.

**Comment by vdemedes** [comment]
Oh I see, I did not understand that at first. Ok, thank you for clarification!

**Comment by sebmck** [comment]
This is no longer relevant as in 3.0.0 I'm removing the blacklist entirely. There's no way to check if the current environment is completely spec compliant and I get issues reporting problems with 6to5 when it's actually the host environment.
