### ISSUE TITLE
Add magic comment to exclude a given section of native-ES6-specific code

### ISSUE THREAD

**Issue by cvrebert** [6to5/6to5#381]
It would be useful if there was a magic comment pragma to make 6to5 delete a section of only-relevant-to-native-ES6 code when doing transpilation to ES5. For example (I don't care what exact syntax you choose):
```js
/* 6to5 delete:start */
// Anything in there will be omitted from the resulting transpiled JS.
/* 6to5 delete:end */
```

**Comment by sebmck** [comment]
You want it deleted completely? What's a possible use-case?

**Comment by cvrebert** [comment]
So, I basically want to write:
```js
let $ = (function () {
    try {
        import * as jQuery from 'jquery';
        return jQuery;
    }
    catch (importErr) {
        const globaljQuery = window.$ || window.jQuery;
        if (!globaljQuery) { throw new Error('I need jQuery'); }
        return globaljQuery;
    }
})();
```
However, `import`s are only allowed at the top-level within a strictly-ES6-spec-compliant module. So, the workaround I am thinking of is something like:
```js
/* 6to5 if es6 */
import * as $ from 'jquery';
/* 6to5 elif es5 */
var $ = (function () {
    try {
        return require('jquery');
    }
    catch (importErr) {
        // same as previous example
    }
})();
/* 6to5 endif */
```
So, I guess some form of conditional compilation would be best, but I'll take whatever I get.

**Comment by sebmck** [comment]
What's wrong with just

```javascript
import $ from 'jquery';
```

turning into

```javascript
"use strict";

var _interopRequire = function (obj) {
  return obj && (obj["default"] || obj);
};

var $ = _interopRequire(require("jquery"));
```

I'm not sure I understand why exactly you want to do what you want to.

**Comment by cvrebert** [comment]
I want to be able to generate a version of my module that works with global jQuery, for folks not using any module system.

**Comment by timoxley** [comment]
It might be easier to create different entry points/builds for the different systems, rather than trying to do it all-in-one.

**Comment by fkling** [comment]
This seems to be rather unrelated to what 6to5 does. I don't think it's a good idea to add this feature.

There is already a package which does something like that: https://www.npmjs.com/package/preprocess

**Comment by thejameskyle** [comment]
@cvrebert I use preprocess for this as well. I have a [`_wrapper.js`](https://github.com/hackbone/namespace.js/blob/master/src/_wrapper.js) file which includes the [library](https://github.com/hackbone/namespace.js/blob/master/src/namespace.js), then I [omit ES6 modules](https://github.com/hackbone/namespace.js/blob/master/gulpfile.js#L20) from the [output](https://github.com/hackbone/namespace.js/blob/master/dist/namespace.js).

We've [discussed adding globals](https://github.com/6to5/6to5/issues/119#issuecomment-61430514) to the UMD module formatter in the past, but there's a bunch of things we'd need to figure out in order to support it.

**Comment by cvrebert** [comment]
I guess I'll just give up on strict ES6 compliance and disable JSCS until https://code.google.com/p/esprima/issues/detail?id=619 gets fixed & propagated.
