### ISSUE TITLE
`export default` bloats exported object

### ISSUE THREAD

**Issue by ooflorent** [6to5/6to5#418]
`export default` does not work as expected 
```js
// test.js
let Test = {
  test() { return 'ok' }
}

export default Test
export let test = () => 'ko'
```

```js
// main.js
import Test from './test'
import assert from 'assert'

assert.equal(Test.test(), 'ok') // AssertionError: "ko" == "ok"
```

**Comment by sebmck** [comment]
You might already know this but it's because it transpiles into the following:

```javascript
var Test = {
  test: function test() {
    return "ok";
  }
};

exports["default"] = Test;
var test = exports.test = function () {
  return "ko";
};
module.exports = _extends(exports["default"], exports);
```

Basically, it's really difficult/impossible to accurately have common interop where default exports are `module.exports` while also having other named exports. Previous behaviour was to only set `module.exports` and set to `exports["default"]` if there were any other non-default exports. I'm starting to feel as if this behaviour is more natural/valid and may revert in 3.0.0. I'm open to other possible solutions though if anyone has them.

**Comment by ooflorent** [comment]
I understand why it was done this way, thus it is possible to import an ES6 module from an ES5 module.
Maybe a flag can be added to turn off common interop?

**Comment by sebmck** [comment]
Previously there was `common` and `commInterop` and then just `common` and `commonStrict`, the latter doing the behaviour that you described. Either the `commonStrict` formatter will be added back or the current behaviour will be changed for 3.0.0.

**Comment by ooflorent** [comment]
Ok, so I will have to wait for 3.0.0 to get this fixed?

**Comment by sebmck** [comment]
Only for changing the current `common` modules behaviour. If a `commonStrict` module formatter was added back a major version bump wouldn't be necessary and I'd just release it in a minor.

**Comment by sebmck** [comment]
Thanks! Added `commonStrict` module formatter as of 2.8.0.
