### ISSUE TITLE
import * with coreAliasing enabled treats namespace object as default export

### ISSUE THREAD

**Issue by AluisioASG** [6to5/6to5#421]
As said in the title; see the test case below for an example.  It seems that happens because the `obj.constructor === Object` check in `_interopRequireWildcard` is transformed into `obj.constructor === _core.Object`, however:
```js
> _core.Object
{}
> Object
[Function: Object]
> _core.Object === Object
false
```

Test case, with ES5-generated code omitted for brevity:
```js
// export.es6
export default function a() {}
export function b() {}

// import.es6
import {inspect} from 'util'
import * as exp from './export'

console.log(inspect(exp))
```
```sh
$ node import-without-core-aliasing.js
{ default: [Function: a], b: [Function: b] }

$ node import-with-core-aliasing.js
{ default: { default: [Function: a], b: [Function: b] } }
```

I'm using 6to5 2.8.2 and core-js 0.4.1, with the `commonStrict` module formatter.

**Comment by monsanto** [comment]
Currently `Object`, `Array`, `String`, and friends are getting transformed by the `new Promise -> new _core.Promise` case, which messes up interaction w/ literals (and objects created from libraries not transformed by 6to5). @sebmck should that be `t.isNewExpression(parent)` instead of `!t.isMemberExpression(parent)`?

**Comment by sebmck** [comment]
@monsanto Nope, it was to also support stuff like `Symbol()` although I completely negleted to consider this scenario happening. I'll have to add in a special case for `Symbol` and only make the direct access in `new`.
