### ISSUE TITLE
Regenerator esprima generated ast discrepancy 

### ISSUE THREAD

**Issue by amasad** [6to5/6to5#473]
Esprima has an old bug that makes it put the `CatchClause` node in a `handlers` field on the TryStatement node, whereas the official Mozilla Parser API defines it as a `handler` property -- which acorn does just fine.

This makes 6to5 unable to print try/catch statements generated by regenerator. To reproduce:
```
$ 6to5 --include-regenerator
function *x() {}
```
Observe the regenerator runtime stripped out from all it's catch clauses.

cc @benjamn maybe this can be fixed in ast-types

**Comment by amasad** [comment]
A link to the esprima bug https://code.google.com/p/esprima/issues/detail?id=433

**Comment by benjamn** [comment]
You can use `require("ast-types").getFieldValue(node, "handler")` and it will work even if `node.handlers` is defined instead of `node.handler`, because the default function for `.handler` (the third argument to `.field("handler", ...)`) is defined in terms of `.handlers` (and vice-versa): https://github.com/benjamn/ast-types/blob/fd206070b6ef07940b2ac7128ee5f3c5824928ab/def/core.js#L120-L122

Note that `.handlers` is "hidden" because `true` is passed as the fourth argument to `.field("handlers", ...)`, so `"handlers"` will be omitted from `require("ast-types").getFieldNames(node)` for a `CatchClause` node, but `"handler"` will be included in the list of field names.

In general, if you're using `ast-types`, I would recommend using `getFieldNames` and `getFieldValue` when traversing an AST, in order to avoid certain inconsistencies like this one.
