### ISSUE TITLE
Debugging 6to5 in node (w/ 6to5/register) is faulty

### ISSUE THREAD

**Issue by MadaraUchiha** [6to5/6to5#481]
Hey! When I try to debug a line on a project that uses `6to5/register` to import ES6 modules, the code runs correctly, but debugging it with breakpoints becomes impossible:

 - Breakpoint breaks on the correct line, but it's not the same line from source code that's executing.
 - Stepping over/in/out jumps to wrong lines (or doesn't jump at all)
 - Stack trace shows something else entirely

I've made a simple showcase for this, available [here](https://github.com/MadaraUchiha/6to5-bug-showcase)

**Comment by sebmck** [comment]
How are you setting the breakpoints, via the node debugger?

**Comment by MadaraUchiha** [comment]
I tried both with Node's native debugger, and with Intellij's debugger (which just calls the native debugger under the hood and does fancy things with it)

**Comment by fkling** [comment]
Are you using source maps?

**Comment by sebmck** [comment]
Yeah, unfortunately there's not really anything we can do about that since we can't influence the mapping of lines in environments that don't support it. There's a [StrongLoop debugger](http://strongloop.com/strongblog/announcing-a-new-and-improved-node-js-debugger/) that supposedly supports sourcemaps but I can't confirm it's validity. I wish there was something we can do about it but unfortunately we can't.

**Comment by FGRibreau** [comment]
I had the same issue than @MadaraUchiha, that's such a bumer for using ES6 with Node.
https://github.com/evanw/node-source-map-support#node-support may be a solution right @fkling @sebmck?

**Comment by sebmck** [comment]
@FGRibreau Source maps are already enabled by default the original source location is mapped when using `babel/register` and `babel-node`. It's unrelated to breakpoints.

**Comment by FGRibreau** [comment]
@sebmck hum, still it does not work as expected:

server.js: 

```
require('babel/register')({
	sourceMap: 'inline',

	// include superfluous whitespace characters and line terminators
	compact: false
}); // allow es6
require('./a');
```

a.js

```
/**
 * [description]
 * @return {[type]} [description]
 */
var a = () => {
	console.log('ok');
	/**
	 * dqsd
	 * @param  {[type]} ( [description]
	 * @return {[type]}   [description]
	 */
	(() => {
		(() => {
			(() => {
				throw new Error('plop'); // should print at ..../a.js:15:11
				// but prints ..../a.js:17:11
			})();
		})();
	})();
};


a();
```

```
node server.js
ok
Error: plop
    at [...]**/a.js:17:11**
    at [...]**/a.js:19:6**
    at [...]**/a.js:20:5**
    at a ([...]**/a.js:21:4)**
    at Object.<anonymous> ([...]/a.js:24:1)
    at Module._compile (module.js:456:26)
    at normalLoader ([...]/node_modules/babel/lib/babel/api/register/node.js:102:5)
    at Object.require.extensions.(anonymous function) [as .js] ([...]/node_modules/babel/lib/babel/api/register/node.js:115:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

As a user, I thought the compiled code would map to the right orginal line number but it does not

**Comment by sebmck** [comment]
Why are you using the `sourceMap` and `compact` options?

**Comment by FGRibreau** [comment]
@sebmck I tried to force them (reading the docs) but without success. I did not started to read babel code however (but I will)

**Comment by FGRibreau** [comment]
@sebmck I tried to force them (reading the docs) but without success. I did not started to read babel code however (but I will).
Hum I see, without these it works. I will find another example where it does not, because I had this issue previously

**Comment by sebmck** [comment]
Yep setting `sourceMap` to `"inline"` will break it because the API will no longer return the sourcemap and instead embed it in the returned code.

**Comment by FGRibreau** [comment]
Indeed! I will come back to you once I can reproduce the issue :)

**Comment by drieks** [comment]
Hi all,
I like to write ES6 Code and want also to use ES6 for for my NodeJS Server Code. I want to contribute a debugging instruction and patches to support debugging if necessary. But I don't understand why this is not already working.

Here:
https://github.com/babel/babel/blob/master/src/babel/api/register/node.js#L59-L62
the `sourceMap` Option is always set to `true`.

This will force the example of @FGRibreau to be a "no op" because the sourceMap option is passed to this lines but then overwritten.

server.js:
```
require('babel/register')({
    sourceMap: 'inline',

    // include superfluous whitespace characters and line terminators
    compact: false
}); // allow es6
require('./a');
```
Thereforce it seems to be intended that his code does not work for debugging.

As @sebmck wrote passing in `"inline"` will break the API.

If I understand it correctly there are two things we need to address: Source Code Linenumber Matching in Stacktraces and breakpoints.

If you pass in `sourceMap: "inline"` breakpoints are working very well, as expected. (at least using `node-inspector` with `node debug`) but linenumber mapping is not working.

To prevent this we can add this line right after the `babel.transformFileSync` call:
```
result.code += '\n//# sourceMappingURL=data:application/json;base64,' + new Buffer(JSON.stringify(result.map)).toString('base64');
```

Then both line mapping and breakpoints are working well with node-inspector.

Nevertheless it does not work with webstorm, I will try to figure this out.

What do you think about this?

**Comment by FGRibreau** [comment]
@drieks "Source Code Linenumber Matching in Stacktraces and breakpoints." was indeed the issue I had with babel/register in a logged stacktrace on nodejs server-side code in production

**Comment by drieks** [comment]
Do you think this line can solve your issue? Are you using breakpoints in production?

**Comment by sebmck** [comment]
So what's the proposed solution/improvement?

**Comment by drieks** [comment]
Please also see Issue #983 for debugging in JetBrains WebStorm/PhpStorm/IntelliJ IDEA)

**Comment by MrOrz** [comment]
I was also struggling with the line number in the stack trace when I use `babel/register`. I've misunderstood the `sourceMaps` option, thinking that `sourceMap: 'inline'` must exist to make error stack line numbers work before I encounter https://github.com/babel/babel/issues/481#issuecomment-75501553 . Maybe adding a short note in the documentation of `sourceMaps` would help others from making the same mistake.

**Comment by danbucholtz** [comment]
I am experiencing an issue with the babel/register hook and node-inspector.  I am able to set break points on what I believe to be a source map (non-transpiled code), but often times I cannot place it on the line that I would like.

I have also noticed that the execution jumps around across various different, incorrect lines in node-inspector.

Does anyone have a fix?
