### ISSUE TITLE
Add option to import regenerator runtime just like coreAliasing

### ISSUE THREAD

**Issue by appden** [6to5/6to5#484]
Rather than including it inline (`--include-regenerator`), which causes it to be included in every module when using something like browserify, it would be great to have the option to have it automatically required in the same way as the optional `coreAliasing` transform provides.

I'm trying to build my project as a full self-contained library, which is why I'd like this functionality considering `regeneratorRuntime` will no longer need to be global (https://github.com/facebook/regenerator/pull/167).

**Comment by sebmck** [comment]
Related #446

**Comment by amasad** [comment]
This is related to my idea around writing the runtime library to a file in the `outDir` that other modules can require. This way we don't have any globals but also don't have to worry about the runtime size. And will avoid taking regenerator and 6to5 as a dependency.

Alternatively, we can have a to5runtime npm package that includes all the runtime and then in the generated code we require the part of the runtime that we need, e.g. `require('to5runtime/extend')`. Hoewver, this could be a versioning nightmare, which is why I think writing to disk is best.

**Comment by sebmck** [comment]
@amasad I'm not quite sure how you envision the runtime library thing. Do you mean just a prebuilt polyfill and regenerator runtime?

**Comment by amasad** [comment]
Yes, plus the 6to5 "runtime". (i.e. the functions that are currently inlined by default or can be gotten by running 6to5-runtime)

**Comment by sebmck** [comment]
@amsad Ah right. Would you expect this to be exported or provided as globals?

**Comment by amasad** [comment]
I'm thinking exported. If the module would be `require`d then no real reason for making it globals. What do you think?

**Comment by sebmck** [comment]
That sounds reasonable. Pretty sure @AluisioASG is working on a PR that does this/something similar so I'll have to wait on that before I do anything.

**Comment by sebmck** [comment]
Closed via #536

**Comment by amasad** [comment]
Great. Is there documentation for this?

**Comment by sebmck** [comment]
@amasad Not yet, it's due for 3.0.0 since it removes `coreAliasing` and the optional runtime.

**Comment by amasad** [comment]
ah, cool, how far away is 3.0.0?

**Comment by sebmck** [comment]
I'm just waiting on some upstream changes for better JSX interopability (right now there are a couple of inconsistencies between the behaviour of `acorn-jsx` and `esprima-fb`). The only other blocker is `regenerator` which I've now [forked](https://github.com/6to5/regenerator-6to5) because of interopability issues with it and recast.

**Comment by amasad** [comment]
I can help on both those fronts, are there an open issues for them?
I'm generally not against forking but since we own both these projects, I can help you fix issues.

**Comment by sebmck** [comment]
The fork was discussed in [#437](https://github.com/6to5/6to5/issues/438#issuecomment-70565071). Basically it's either `regenerator` expecting comments to be the same format as `recast` or `regenerator` destroying node metadata inadvertently expecting `recast` to be able to reconstruct it. I don't particularly think these are issues that need to be resolved upstream because I think the maintenance burden of supporting these edgecases should be on me.

**Comment by amasad** [comment]
Ok this makes sense if you're tracking upstream.
As for the parser, what was the reason for not using esprima-fb to begin with?

**Comment by sebmck** [comment]
6to5 actually used recast and `esprima-fb` initially until I eventually moved to `acorn` then `acorn-jsx` and now `acorn-6to5` which has flow type support, more ES7 support, playground features etc.

I hacked in `acorn` into `recast` with 6to5/6to5@1f274a3b958f22a755f6ee875049ce6728b562c6 because I got sick of issues with poor ES6 support, I couldn't contribute either then because my knowledge of parsers was non-existent. Another reason was performance, `acorn` is **much** faster, even though parser overheard isn't the main performance issue with 6to5.

**Comment by sebmck** [comment]
Also the code of `recast`, still to this day, confuses the hell out of me.

**Comment by amasad** [comment]
There is no real dependency of esprima-fb on recast. But I agree that esprima is a very slow moving project (that's why we forked it).

**Comment by sebmck** [comment]
@amasad You have to use the `recast.parse` API if you want the "conservative" functionality though which is what 6to5 originally used it for.

**Comment by sebmck** [comment]
3.0.0 has been released including a [selfContained](http://6to5.org/docs/usage/transformers/#self-contained) transformer.

**Comment by amasad** [comment]
Sweet! that's exactly how I was envisioning it.
