### ISSUE TITLE
`import` cannot import Joi

### ISSUE THREAD

**Issue by jakecraige** [6to5/6to5#493]
I was attempting to import [Joi](https://github.com/hapijs/joi) like

```js
// what I had
var Joi = require('joi');

// changed to
import Joi from 'joi';
```

Which caused some weird errors like this and my app wouldn't run. 

```
TypeError: Object function (value) {
    var obj = this.clone();
    obj._flags.default = value;
    Ref.push(obj._refs, value);
    return obj;
} has no method 'number'
```

Turns out that Joi provides a `default` method  so the _interopRequire returns that instead of the main object

```js
var _interopRequire = function (obj) {
  return obj && (obj["default"] || obj);
};
```

Other than Joi not exposing a `.default` method, I can't see any way this could be fixed. So I'm just using node's require for now. I just wanted this to be searchable for anyone who came across this issue. 

One possible solution would be for 6to5 to use a different name for the default export, like `_default`. Even with that though there is still the possibility of a naming conflict. I can't think of any real nice solution off the top of my head.

**Comment by thejameskyle** [comment]
Ping @guybedford

**Comment by thejameskyle** [comment]
We could test that default isn't a method, but that'll only fix this particular case.

**Comment by eventualbuddha** [comment]
@thejameskyle `default` is probably quite often a function, e.g. `export default (function|class) …`.

**Comment by thejameskyle** [comment]
Welp.

**Comment by sebmck** [comment]
See #95 #224 #225 #242 for module interop issues. It's a hard problem to solve elegantly.

**Comment by guybedford** [comment]
I'm not sure I understand what the issue is here at all? Surely `import * as Joi from 'joi` is the syntax to use?

**Comment by sebmck** [comment]
@guybedford joi doesn't export a plain object so it skips the `obj.constructor === Object` check in `interopRequireWildcard`. Perhaps this check needs to be more lazy and just check that `typeof obj === "object"`.

**Comment by guybedford** [comment]
@sebmck ah right, I thought Joi was ES6 not CommonJS as it had a default export.

Best not to use `import *` then, as it doesn't make sense for loading CommonJS (`{ default: cjsModule }` is the base representation of this object, and can be extended with the exports as well if you like).

Handling default exports from CommonJS does kind of break the interop require assumption. Perhaps another argument for an `__esModule` flag?

**Comment by sebmck** [comment]
@guybedford Yeah it definently is another argument for that flag. I'm going to do a major release soon so I can change a bunch of things so it'd be a good time to change any module behaviour.

**Comment by sebmck** [comment]
I'm not sure if there's a way to solve this without breaking current module interoperability (which isn't worth it), open to suggestions though.

**Comment by guybedford** [comment]
@sebmck that makes sense if backwards-compatibility is important. You can add a flag without affecting interop today, then that opens up the possibility of generating code that assumes it given enough time in future (perhaps a year or two will be enough). If an unobtrusive flag is wanted perhaps something like `__es: true`?

**Comment by Marsup** [comment]
Wouldn't it be wiser to go with the same flag as traceur (`__esModule`) to be compatible with modules produced with it ?

**Comment by sebmck** [comment]
@Marsup See #95 for previous discussion on why the current module behaviour is the way it is.

**Comment by sebmck** [comment]
The issue is that in order to have a solid common interop you need to be setting default exports to `module.exports`. This makes it impossible to have an `__esModule` flag because there's no `default` property as it's not necessary.

**Comment by guybedford** [comment]
@sebmck are you talking about the rule of a single default ES6 export as the only export being treated as `module.exports`? In this case, the module will load exactly as expected without a flag, even in flag-based interop expectations like Traceur's CommonJS output.

It's difficult to argue against real code that exists in the wild, but yes we can certainly draw a line.

**Comment by nkt** [comment]
What about add option for disabling any wrappers and use just `require` instead? Or there are `common`, `commonStrict` modes, so let's add `commonRaw`?

**Comment by sebmck** [comment]
Two variants of UMD, AMD and Common is already enough without needing a third. I'll revisit this post-3.0.0.

**Comment by nkt** [comment]
Why you not use just require? Is this BC with old 6to5 versions, where `export default` converts to `export.default = ` ?

**Comment by guybedford** [comment]
I suppose the workaround here is just to use named exports for these cases?

**Comment by mpal9000** [comment]
Temporarily I'm using:
```javascript
import * as _Joi from 'joi';
let Joi = _Joi.default;
```

**Comment by guybedford** [comment]
@mpal9000 does it not work if you do `import {array} from 'joi'`? I would have expected that would work ok, and it is syntax that is compatible with what is expected I believe.

**Comment by mpal9000** [comment]
@guybedford yes it works like this, but usually you want all or many of those validation functions, so you have to write `import { array, object, boolean, date, etc } from 'joi'` which is not very practical and the purpose of named imports is to pick only a few exports. By the way thank you for all your work in the modules area!!

**Comment by sebmck** [comment]
In 3.0.0 `module.exports` will **only** be set if there's a single default export otherwise an `__esModule` export will be set and the default exported with the `default` property.

**Comment by sebmck** [comment]
@guybedford @UltCombo raises some goods points regarding having any common interop at all:

> @sebmck IMHO attempting CJS interop is what will actually bite people in the ass. A non-obvious breakage that can happen due a simple dependencies update (as in my example above) will be a pain in the ass to debug.
>
> A better approach would be to have CJS code to explicitly retrieve the default property, e.g.:
>
> ```javascript
> var es6module = require('./es6module')['default'];
> ```
> 
> Then there's no breakage and no need for __esModule flag hacks.

What are your thoughts?

**Comment by UltCombo** [comment]
(the "example above": https://github.com/6to5/6to5/issues/587#issuecomment-71348484)

**Comment by sebmck** [comment]
I'm just going to remove the common interop. There are too many issues associated with maintaining it and it's easier and more straightforward to just export to `default`.

**Comment by UltCombo** [comment]
Agreed. Less magic is better in the long run.

**Comment by sebmck** [comment]
To the people who are upset with this change, just continue using CommonJS if that's the environment you're targeting.

**Comment by sebmck** [comment]
Actually ugh, I'm really not sure about this. I'm extremely conflicted.

**Comment by sebmck** [comment]
I'm holding off on everything until @guybedford can chime in because I'm interested in his take on this all.

**Comment by impinball** [comment]
# Idea

Exports should remain like this:

```js
export foo;
export {foo};
// compiles to
exports.foo = foo;

export default foo;
// compiles to
exports.default = foo;
```

## Call types

With interop:

```js
import foo from 'bar';
import * as foo from 'bar';
// compiles to
var foo = require('bar');

import {foo} from 'bar';
// compiles to
var foo = require('bar').foo;
```

Without interop:

```js
import * as foo from 'bar';
// compiles to
var foo = require('bar');

import foo from 'bar';
// compiles to
var foo = require('bar').default;

import {foo} from 'bar';
// compiles to
var foo = require('bar').foo;
```

## How to compile, based on target

Compile with/without interop = corresponding call type above

1. If the target module is in a dedicated blacklist, compile without interop.
2. If the target module cannot resolve as a JavaScript module (not in list of accepted extensions), compile with interop.
3. If the target module is a relative require, compile without interop.
4. If the target module is in the same node_modules directory as the calling module, compile without interop.
5. If the target module is from a dedicated whitelist directory or file, compile without interop.
6. Otherwise, compile with interop.

**Comment by sebmck** [comment]
@impinball Seems like a complicated solution when the real issue is how do you handle named exports and default exports at the same time.

**Comment by impinball** [comment]
I suggest it because obviously, CommonJS interop mode can fail, and it is dependent on the module being imported. The steps are mostly heuristics based on common patterns. I'm seeing it as an issue of CommonJS interoperability (or lack thereof). The issue isn't that default exports and named exports aren't being properly handled at the same time; it's accounting for a difference in idioms where compiled ES6 modules differ from the standard CommonJS (and others) idioms.

```js
// CommonJS

// default export
module.exports = foo;

// named export
exports.bar = bar;
foo.bar = bar;
module.exports.bar = bar;
```

```js
// ES6 idioms

// default export
export default foo;

// named export
export {bar};
```

```js
// Compiled ES6

// default
exports.default = foo;

// named
exports.bar = bar;
```

Or, to put the compiled ES6 and CommonJS side-by-side (all using `module.exports` in this case):

```js
// Herein lies the problem
module.exports = foo;
module.exports.default = foo;

module.exports.bar = bar;
module.exports.bar = bar;
```

The top part is the core of the issue here, the difference in idioms. I was proposing a way to work around it, where certain idioms are used for certain cases, but not others.

The other option I can think of is accepting an explicit regex option to select which targets to compile `import foo from 'bar'` and `import * as foo from 'bar'` as straight `require`s.

I edited my initial proposal, since it wasn't entirely complete and clear initially.

**Comment by sebmck** [comment]
@impinball My concerns are with adding in magic and complicated behaviour for module behaviour. Basing behaviour on module paths doesn't make a whole lot of sense and is bound to run into issues and complications.

**Comment by guybedford** [comment]
@sebmck an `__esModule` flag solves this specific edge case where a `exports.default` is used in CommonJS, which was an edge case we accepted as part of the heuristics.

The ability to load named exports from existing CommonJS modules is an extra feature we added to the interop so that `import { readFile } from 'fs'` would work. This case can still be reconsidered.

Note that the `require('m').default` convenience (loading single-export ES6 from CommonJS) is a largely orthogonal concern to loading CommonJS from within ES6. They are two separate approaches which are both being used in the interop format.

Adding linking behaviour is certainly an option like @impinball suggests, but yes it adds even more complexity to an already complicated area to understand.

For me, the main interop issue is just allowing ES6 compiled into CommonJS to load from other CommonJS (`import fs from 'fs'`), and if we don't do a basic interop, then there isn't a nice upgrade path as users would naturally write `import * as fs from 'fs'` which is an invalid upgrade path.

**Comment by sebmck** [comment]
@guybedford I've added in the `__esModule` flag in 3.0.0, I'm just trying to wrap my head around how things can be simplified further. I couldn't recall whether or not the points that @UltCombo bought up were a worthy sacrifice or not. Thanks for clearing it up, I'm just trying to get on top of all this as I want to have it all sorted for the 3.0.0 release.

**Comment by UltCombo** [comment]
> Actually ugh, I'm really not sure about this. I'm extremely conflicted.

Everyone has been conflicted about this for a good while, that's why I advocate to keep things simple.

Anyway, if I'm reading the #587 discussion correctly, most issues can be solved by fixing the `__esModule` flag logic.

As for the `import { readFile } from 'fs'` use case, I don't know if it is something worth supporting, taking in consideration that:

1. CJS modules only have a single (default) export, it has no concept of named exports.

1. As soon as the given environment (Node/browser) supports ESM semantics, trying to import any native ESM module will break due to the interop code looking for a non-existent `__esModule` flag.

1. Name conflicts. What if the ESM default export is an object which contains a property with the same name as a named export? The ESM -> CJS interop would only expose one of them.

1. Learning curve, debugging and maintaining toll (for both users and interop developers) -- how to explain to users that their ESM syntax "simply works" with CJS, except in certain cases, and that [some features](https://github.com/6to5/6to5/issues/587#issuecomment-71371133) are not compatible?

I personally would rather not depend on some magical interop. If my code consumes CJS modules (e.g. Node.js modules) then so be it, use the proper CJS semantics and there are no problems whatsoever. That's what we do in [Harmonic](https://github.com/es6rocks/harmonic/blob/master/src/bin/parser.js).

I don't really oppose if you guys want to keep pursuing the interop El Dorado, but I'd like to keep using the (far simpler, less magical) `commonStrict` transform in my ES20xx generator, in order to ship modules with saner defaults that won't break in obscure ways in the future.

**Comment by UltCombo** [comment]
(Point 2 above refers to compiling ESM -> ESM and still having interop to `import` both ESM and CJS formats, but I'm not sure if this concerns any of you)

Anyway, my point is, why put so much effort into this complex logic risking leaving out many edge cases, just to be able to do this:

```js
import { readFile } from 'fs';
```

When you can already have the same expressive power with:

```js
let { readFile } = require('fs');
```

I just don't see the point, as far as I can see this is just unnecessary syntactic sugaring that adds complexity and, consequently, unforeseen bugs.

**Comment by guybedford** [comment]
@UltCombo for point 2 I've long been advocating a `Reflect.isModule` function and have posted three times to es discuss about this but no one has backed me up. Ideally we would output a check that does both `__esModule` and `Reflect.isModule`.

The thing to note though is that this scenario only happens when a CommonJS-published module is updated to be ES6 as a non-breaking change and a published transpiled ES6 module is loading from it. This is very unlikely though as one would expect publishing ES6 to be a breaking change and would re-evaluate dependencies. If we want to load real ES6 from ES6 transpiled to CommonJS in an ES6 environment, we're better off writing ES6 anyway.

So in both the above scenarios I don't see it being an issue. But do let me know if I'm missing something other cases.

I'm on the fence about the allowing of `import { readFile } from 'fs'`, we can make it work either way. In real ES6 environments, it just means the interop layer does the `_default` step, which we could add to something like SystemJS.

**Comment by guybedford** [comment]
@UltCombo I'm against writing code that combines ES6 modules and require syntax, as that code won't be compatible with loading in a dynamic ES6 module loader. That's why we had to tackle this interop head-on for SystemJS.

**Comment by mpal9000** [comment]
> To the people who are upset with this change, just continue using CommonJS if that's the environment you're targeting.

I believe that modules handling should be common in 6to5 and Traceur, with the same end result, so modules can be used in the same way by users of both tools. 6to5 and Traceur are the two major tools for transpiling js.next to js of today. A common usage will make the transitioning to the real native modules easier for all of us. Even if the transition won't be fully transparent, a single new formatting tool could apply once to existing code, when the time comes. The transpilation to commonjs is the most successful way of using native modules today, simply because it works well with npm/node/io. And for the browsers there are great tools like browserify and webpack. Using commonjs directly in a js.next codebase is not nice and future proof for me. Native modules is the feature that will be supported by engines after all the others, so a common approach from the transpilers will help us to use successfully one of the best es.next features today.

**Comment by UltCombo** [comment]
> for point 2 I've long been advocating a `Reflect.isModule` function and have posted three times to es discuss about this but no one has backed me up. Ideally we would output a check that does both `__esModule` and `Reflect.isModule`.

Yes, I recall seeing it once or twice. I believe not many have sailed these interop seas for as long as you have, so they don't see as much necessity or are waiting for a "better" solution to show up.

> I'm against writing code that combines ES6 modules and require syntax, as that code won't be compatible with loading in a dynamic ES6 module loader. That's why we had to tackle this interop head-on for SystemJS.

@guybedford what are the incompatibilities when the target environment already provides CJS support?

**Comment by UltCombo** [comment]
> Using commonjs directly in a js.next codebase is not nice and future proof for me.

@mpal9000 what exactly is "not future proof"? I assume you don't mean Node/io dropping CJS support and breaking the 100,000+ current npm packages.

So I'll assume you're talking about a browserify/webpack/SystemJS/etc workflow. Even in that case, the tools you're currently using will not simply rot away, they will still be there for as long as you need them. I don't see how CJS is "not future proof", in fact, it is a well spec'd and [largely implemented](http://wiki.commonjs.org/wiki/Implementations) standard.

You may say using multiple module formats is ugly, looks dated or whatever, but saying CJS is "not future proof" is completely flipping the coin here -- using magical non-spec'd interops that you can only hope that will still work by when you wake up the next morning is what is not future proof here.

**Comment by guybedford** [comment]
Having ES6 being able to load other formats is a core design in the loader spec. If we're going to have a native module loader in the browser it must be able to support existing modules today, and since transpiling CommonJS into ES6 universally is not possible since circular references break, the only option for real adoption is to enable ES6 to load CommonJS. Thus this interop.

As this happens, then if Node wants to see modules that work in the browser also work in Node then it should support that same interop as well.

In the mean time, if we've populated the ecosystem with lots of modules that combine syntaxes then the dynamic story about does break, and the whole thing falls apart yes - hence my resistance!

**Comment by mpal9000** [comment]
> You may say using multiple module formats is ugly, looks dated or whatever

That is what I'm saying. And also that mixing `require`s in es.next codebase will make the transition to native modules harder, when they start being used by the majority. I would like a common solution that works as good as it gets with existing npm modules. CommonJS is great but native modules are better because they are a language feature and will solve the problem of the "many module formats". If the transpilation methods are similar new tools can build upon those, if needed.

**Comment by UltCombo** [comment]
@guybedford thanks for the insightful explanations. `;)`

@mpal9000 

> CommonJS is great but native modules are better because they are a language feature and will solve the problem of the "many module formats"

Agreed, ESM are better and are supposed to end the module formats war. However, as far as I can see there has been little to no public effort from implementators in the cross-loading ESM/other module formats aspect (as backed up by @guybedford's struggle on ES Discuss).

> And also that mixing `require`s in es.next codebase will make the transition to native modules harder. [...] If the transpilation methods are similar new tools can build upon those, if needed.

Neither of us has a crystal ball, but I don't particularly see how `require`s would make the transition harder -- CJS is the de-facto module format for Node, so there will most likely be a straight upgrade path as soon as Node starts supporting ESM (if it ever does).

**Comment by guybedford** [comment]
@UltCombo just to clarify - I explained that the `Reflect.isModule` point is not critical in https://github.com/6to5/6to5/issues/493#issuecomment-71377771. This is a second-degree interop (loading ES6 from transpiled ES6). First-degree interop (loading non-ES6 from ES6) has always been a primary concern for ES6 modules.

**Comment by UltCombo** [comment]
@guybedford I see. I'm aware loading non-ESM from ESM was always/is a primary concern, however there has been so much fuss about System/Loader and hooks in the past and all these discussions are decentralized -- this is very hard to keep up with.

Perhaps, if/when you have time, feel free to submit a post to [ES6 Rocks](https://github.com/es6rocks/es6rocks.github.io) about the current state of modules interop. Perhaps then you wouldn't have to re-iterate all these points in every discussion thread. `;)`

And as you've commented in #95:

> This is a difficult discussion, and most discussions about this tend to reach a stalemate, since you have to go quite far down a road of thought to see where it falls over, so it can be tricky to switch between viewpoints in a single discussion.

So I believe putting all these pieces together in a single place would be extremely useful for those that are joining this topic now, and also to organize all these ideas and approaches in order to help advance one step further.

**Comment by mpal9000** [comment]
@UltCombo The cross-loading is a very useful hack and I don't think that will be ever officially supported. But it is necessary for using native modules syntax today. About the harder transition, I mean that if someone writes in native modules syntax, probably won't need to change anything in the code or apply a new simple formatting tool once to the original code. But if `require`s are being used, then a more complex tool will be needed or a transpilation step. Also if many people are writing in native modules syntax today, will help to be the defacto format faster. As for node/io, I can't see any reason for not supporting ESM in the future (near or far). It's just js and it uses an engine that will certainly support them.

**Comment by UltCombo** [comment]
@mpal9000 

> The cross-loading is a very useful hack and I don't think that will be ever officially supported.

I believe that statement is not quite clear -- the language itself will not support loading other module formats, however the language will provide loader hooks that enable one to load non-ESM module formats IIRC.

> About the harder transition, I mean that if someone writes in native modules syntax, probably won't need to change anything in the code or apply a new simple formatting tool once to the original code. But if requires are being used, then a more complex tool will be needed or a transpilation step.

Well, that depends on exactly what use cases we're referring to. If you're talking about browserify/etc then sure. But as for Node.js, I still hold my point. Node.js's `require` is the built-in/native/vanilla/"non-magic" way to import modules. Nothing will go wrong as long as you use `require`, it is the de-facto Node.js way of modules, and that is what everyone has been using until now. There shall be an easy upgrade path once Node.js starts supporting ESM, otherwise no one would use it.

> Also if many people are writing in native modules syntax today, will help to be the defacto format faster.

Again, it depends on what you're using ESM syntax for. If you're importing ESM/transpiled-ESM, then sure, you're using it appropriately, and in the future you may just as well drop the transpiling step when/if the given environment supports ESM. Now, if you're using ESM to load Node.js core modules (which are currently CJS) then you're relying on some black magic abstraction which seems rather unstable IMHO.

> As for node/io, I can't see any reason for not supporting ESM in the future (near or far). It's just js and it uses an engine that will certainly support them.

Yes, I just meant the "if ever" because, last time I checked, they didn't seem to give a rat's ass about ESM. Of course, V8 should support ESM in the near/far future.

**Comment by UltCombo** [comment]
Some of the points above were not too clear. What I mean is, assuming you're developing a Node package where you transpile all files (except the ones inside `node_modules`):

- Use ESM syntax to `import` files from your own package.
- Use ESM snytax to `export`.
- Use `require()` for core packages and `node_modules` packages.

This is what I've been advocating since the beginning, sorry if it wasn't clear.

**Comment by mpal9000** [comment]
@UltCombo It was clear, and it works correctly. I personally don't like mixing module formats, because there are existing solutions that allows me to use only ESM. I just think those solution should be same between different transpilers.

> however the language will provide loader hooks that enable one to load non-ESM module formats

Right, but I see that as another tool to make the transition easier.

> Now, if you're using ESM to load Node.js core modules (which are currently CJS) then you're relying on some black magic abstraction

Useful hacks like this allow to also use other "black magic" techniques like using core modules in the browser. For me that is very important because I believe that web development with js should be based on isomorphism. JS is the only language that makes this possible without too many tools and compilers.

> Yes, I just meant the "if ever" because, last time I checked, they didn't seem to give a rat's ass about ESM

That's because there are other js.next features that can be implemented first and modules will be the last one. ESM should be first adopted by the browsers, but I believe as developers we can help in the faster adoption by using them where it's possible right now.

The transition will be hard in all platforms, but we should start believing more in the feature's advantages first, to make it easier. Issues like this one are very important, because they bring all our ideas and thoughts to the table.

**Comment by UltCombo** [comment]
>> Now, if you're using ESM to load Node.js core modules (which are currently CJS) then you're relying on some black magic abstraction

> Useful hacks like this allow to also use other "black magic" techniques like using core modules in the browser. For me that is very important because I believe that web development with js should be based on isomorphism. JS is the only language that makes this possible without too many tools and compilers.

Well, I guess this goes a bit off-topic as you don't really need ESM/CJS or any module format to use core modules in the browser (they're JavaScript after all, and JavaScript is pretty much the closest reality to the "Write once, run everywhere" utopia).

But anyway, for comparison's sake, looks like you're hinting at browserify which is just some basic static analysis + bundling, it doesn't have nearly as much black magic involved as these modules interop IMO. To add some reasoning:

- Assume a workflow where you write ES20xx and transpile to ES5, transforming ESM into any other module format (CJS/AMD/something else).
- The transpiler's ESM -> &lt;other module format> transform conciliates ESM `import` and `export` statements across multiple files in a such way that it works as expected in the output module format. How this is done, however, is mostly just an implementation detail.

Now, when we consider that "native" CJS can require our ESM-transpiled-to-CJS code, then the transpilation internals are no longer an implementation detail. This adds some complexity if you want "native" CJS to *pleasantly* consume your transpiled module (e.g. `require('x')` instead of `require('x').default`).

And then you also have to account for ESM syntax being used to import non-ESM-transpiled modules (that is, "native" CJS modules such as core and npm packages). At this point the transpilation implementation logic is split in two, with an added `__esModule` flag to distinguish "native" CJS and ESM-transpiled-to-CJS modules, so that `import` actually exposes different APIs 'cause ESM and CJS are just not compatible at all. And I believe this is just the tip of the iceberg.

**Comment by mpal9000** [comment]
@UltCombo "Requiring" ESM from CJS is another problem, but it's not so bad to write `require('x').default`, if the ES module has a default export. Nevertheless I think that if someone takes the path to use ESM he/she should start write everything with ESM. So there will be no ESM->CJS problem. If someone can't write with ESM syntax for some reason, he/she should use `require('x').default` if needed or use another similar CJS library. About the non-transpiled-ESM->ESM problem, I believe that a common approach from the transpilers will help, because the end product should have to be transpiled at the end.

**Comment by UltCombo** [comment]
@mpal9000 I agree, just note that one can publish ESM-transpiled-to-CJS to npm, in that case those who depend on that package and aren't transpiling their code would have to write `require('x').default`, which is not a big problem in my opinion either.

**Comment by mpal9000** [comment]
@UltCombo Publishing a transpiled ESM version in a "dist" directory with the "main" package.json field pointing to "dist", is a must for me. Until the adoption will be in a good state. Then the consumers can choose how to use it. They can `import` and transpile, they can `require` and transpile or they can `require`. They can also `import`/`require` the from source (not "dist") but then the module path will be different. Even in that case there are tools that can use an "es6main" (or something like that) custom field, but these are experimental tricks which aren't necessary at all.

**Comment by UltCombo** [comment]
> Publishing a transpiled ESM version in a "dist" directory with the "main" package.json field pointing to "dist", is a must for me.

@mpal9000 Oh nice, that's the same structure [slush-es6](https://github.com/es6rocks/slush-es6) generates.

I'm not sure about publishing the source files, transpiling at runtime hurts perf, letting alone source files often rely on transpiler version-specific behavior.

**Comment by mpal9000** [comment]
@UltCombo I will try it! Why not publishing the source. It's the source. Someone can read it, retranspile it (version-specific behavior problem) or use tricks like the one above (not for runtime transpiling - it's bad). Runtime transpiling is only useful for some tools like a repl.

**Comment by UltCombo** [comment]
@mpal9000 Oh, I just didn't see a need to publish the source as it is available in the repository, and not publishing it to the registry provides slightly faster `npm install`s. Anyway, if you like you can include `src` in the [package.json's `files`](https://github.com/es6rocks/slush-es6/blob/b68ecd9d79e411e6fd5c3235a83e758d6b6c41ab/tpl/env/node/package.json#L21-L25) array. `;)`
(I'm changing the structure a bit so there are a couple things to fix regarding `files`)

**Comment by impinball** [comment]
## Second Proposal (which should be a lot simpler)

Allow for a specific blacklist of directories/files in which to fall back to where `import foo from 'bar';` and `import * as foo from 'bar';` are both equivalent to `var foo = require('bar');`, as in they don't compile. Such a test would be trivial, especially with the builtin `path` module (which does no I/O). Here's a literal implementation of checking against that blacklist. It's relatively simple, relying on a hack based on an invariant with any path resolving tool, specifically that if it's not in a descendant directory, it's going to have to go up above it before it can go down to the target. In every Node-supported platform, `..` goes up a directory. The in-code comment explains the hack a little more.

```js
var path = require('path');

function isChild(maybeParent, maybeChild) {
  // If it's not a descendant, you have to go up above it somehow to
  // get to the target module's path. This also works for specific
  // file exclusions, which would amount to '.'.slice(2) being just
  // one dot, not two (and thus fails as a consequence).
  return path.relative(maybeParent, maybeChild).slice(2) !== '..';
}

function inBlacklist(list, moduleName) {
  // This is relatively self-describing.
  return list.some(function (entry) {
    isChild(entry, moduleName);
  });
}
```

The above code would make up >40% of the patch (it would be easy to implement). It would also allow for such exceptions to be specified when the code is compiled. Figuring these things out at runtime *correctly* for *all* cases is impossible as it would solve the halting problem. That's where human input comes in.

Optional blacklists may be the best solution for this case, since it normally Just Works&trade; 99% of the time (and speed isn't usually an issue when importing a module).
