### ISSUE TITLE
Loose option doesn't work with require hook

### ISSUE THREAD

**Issue by phuvo** [6to5/6to5#505]
`index.js`
```javascript
require('6to5/register')({
    loose    : ['forOf'],
    whitelist: ['forOf'],
});
require('./test.js');
```
`test.js`
```javascript
for (let item of [1]) console.log(item);
```
Run with node.js 0.11.14 in Harmony mode:
```
for (let item of [1]) console.log(item);
^
TypeError: undefined is not a function
```

**Comment by sebmck** [comment]
It's actually do to `6to5/register` testing whether or not the current environment supports let scoping, for of etc. Node reports that it supports `for...of` but it currently ships with a broken version. You can reset the blacklist with:

```javascript
require('6to5/register')({
    loose    : ['forOf'],
    whitelist: ['forOf'],
    blacklist: []
});
require('./test.js')();
```

I'm going to remove the blacklist detection in a future version since it's difficult to accurately check the existence of a certain feature and even if we know it exists, it's likely not spec compliant so it'll produce weird behaviour or it'll just be flat out broken as in this case.
