### ISSUE TITLE
Issue with tailing comma and following comments

### ISSUE THREAD

**Issue by qqshfox** [6to5/6to5#544]
#### before

```js
var a = {
  key: "value",
  // comment
};
```

#### after

```js
"use strict";

var a = {
  key: "value" };
// comment      <------------------------------------------------------ problem here
```

This caused a problem when used with `concat` by ';'.

#### before

```js
var a = {
  key: "value"
  // comment
};
```

#### after

```js
"use strict";

var a = {
  key: "value"
  // comment
};
```

**Comment by sebmck** [comment]
Can't fix this due as currently comment attachment is delegated to [estraverse](https://github.com/estools/estraverse). Due to the comma it's getting confused and can't find a sibling node to attach it to because suddenly there's an additional token that's not a part of a node. This may change in the future once 6to5 eventually implements it's own comment attachment but right now it's not a priority.
