### ISSUE TITLE
Make it possible to transpile ES7 to ES6.

### ISSUE THREAD

**Issue by bolinfest** [6to5/6to5#581]
Or to word this another way: "Make it possible to specify a list of transformers that parse and preserve their input, but do not transform."

I realize this sounds weird, so let me explain what I am trying to do.

I am using 6to5 (with `experimental`, `includeRegenerator`, and `reactCompat` enabled) to transpile my ES7+JSX code to ES5 so I can run it in [Atom](https://atom.io/). That works really well.

However, I also want to use 6to5 to transpile my ES7+JSX code to ES6 that I can lint my source with [ESLint](http://eslint.org/). For ES6 features that ESLint recognizes, I do not want them transpiled. By making the delta between my ES7 and ES6 code smaller, it makes ESLint more valuable.

Specifically, if the original version of my source has a defect that would be flagged by ESLint, but 6to5's transpilation rewrites my code to clean up the defect, that's bad because then I am not able to leverage ESLint to find that defect.

There is also the issue that some of the transpiled code does not satisfy ESLint today. For example, if I use ES6 class inheritance in one of my source files, I end up with the following in the transpiled output:

    if (superClass) subClass.__proto__ = superClass;

This gets flagged by [ESLint's `no-proto` rule](http://eslint.org/docs/rules/no-proto.html). Obviously I could disable this rule in ESLint, but I would rather not.

It would also be nice if there was an option to preserve the quoting style in the input in the output for the same reason. Because all of the output contains double-quoted strings, I get a ton of ["Strings must use singlequote"](http://eslint.org/docs/rules/quotes.html) warnings from ESLint.

In addition to linting, I think there are long-term benefits her. As environments start to support ES6 features natively, it would be nice to disable 6to5's rewriting of those features. Again, it makes the delta between input and output smaller, and in cases where JS engines have been optimized for some of the new language features, it would make it possible to leverage them.

Thoughts?

**Comment by sebmck** [comment]
All the 6to5 transformers can be disabled/enabled at will. See the whitelist and blacklist options detailed [here](http://6to5.org/docs/usage/options/). With 3.0.0 all the transformers are going to be namespaced so I might add the ability to also specify namespaces in transformer lists.

I've thought about automatically detecting string quotation but there comes the issue of what quotes you use when there aren't any in the original source but 6to5 has had to insert a string literal somewhere. I really wish that espree wasn't a total rewrite because if they used something like acorn and esprima they could've pulled from upstream where all these features are already supported as they obviously can't keep up with maintaining both it and ESLint.

**Comment by bolinfest** [comment]
@sebmck So if my input is:

```js
class Foo extends Bar {}
```

what flags would I pass so that my output is still:

```js
class Foo extends Bar {}
```

Would I have to add `classes` to the `whitelist`?

**Comment by sebmck** [comment]
Add it to the blacklist so `6to5 --blacklist classes` or `require("6to5").transform("code", { blacklist: ["classes"] })`

**Comment by bolinfest** [comment]
@sebmck Thanks for the help! Now that I got my options working correctly (https://github.com/6to5/6to5/issues/583), everything works beautifully, and exactly as you described.

I'm also starting to see what you mean about the Espree situation. It appears to be very far behind as an es6 parser. This is making it hard to derive any value from ESLint in my situation. It seems like 6to5 does too nice a job cleaning up my code, such as adding forgotten semicolons to the end of my lines. This means that I can't lint the output to find where I have missing semicolons in my source!

I think that I might try running 6to5 with a large es6 blacklist. Basically, the only thing I will have it convert is the es7 stuff. Assuming that doesn't clean up my code that much in the process of transforming it, perhaps I can then run jstransform on the output of 6to5 and run ESLint on that.

**Comment by sebmck** [comment]
@bolinfest No problem! You could probably fork ESLint and replace `espree` with `acorn-6to5` as they both produce the same Spidermonkey AST. Only issue would be that ES6 nodes probably wouldn't be traversed and errors on them would be ignored. If espree was a fork of the esprima harmony branch or even of esprima-fb then they would've saved themselves a lot of trouble instead of trying to maintain yet another parser.

**Comment by xjamundx** [comment]
Hey friends. I sometimes contribute to eslint/espree. Want to throw a few things out there, to make sure we're not way off.

1. espree is a fork of esprima, we're just pulling in all of the es6 features from the esprima harmony branch (with very few changes, mostly fixing bugs and adding more tests).
2. there are several devs working on it pretty heavily and each week several new es6 features get added (see: https://github.com/eslint/espree/issues/10)
3. you can't just straight swap out espree, because the esprima-fb and acorn-6to5 break a number of things such as the way comments and line numbers are handled AFAIK, so it breaks existing modules. (see this huge thread for more details: https://github.com/eslint/eslint/issues/1291#issuecomment-64103087)

I love 6to5 and eslint so I'd be happy to offer any help to get everyone closer together. AST parsers are forking like crazy :)

**Comment by sebmck** [comment]
@xjamundx Acorn supports the entirety of the ES6 spec and is 2x faster than esprima. There's no benefit to adopting esprima at this stage.

**Comment by xjamundx** [comment]
Oh yeah sorry wasn't suggesting at all that you move to that, just clarifying stuff!

**Comment by niieani** [comment]
There is a use case which is not covered by disabling specific transformers.
When I turn off "regenerator", I also loose the ES7 "async/await" support.
It would be useful to have the ES7 "async/await" transpiled to ES6 (built-in generator support) for use in targets that support generator functions natively (like io.js).

**Comment by sebmck** [comment]
@niieani You already can :smile: See [bluebirdCoroutines](http://babeljs.io/docs/usage/transformers/other/bluebird-coroutines/) and [asyncToGenerator](http://babeljs.io/docs/usage/transformers/other/async-to-generator/).

**Comment by niieani** [comment]
@sebmck That's awesome. :+1:  It should be easier to find in the docs though (and perhaps a bit clearer). I was looking all over the website and couldn't find that, hence I wrote here on GitHub. 
Great job!
