### ISSUE TITLE
Automatically import react when using JSX

### ISSUE THREAD

**Issue by sebmck** [6to5/6to5#586]
Avoids the cognitive load of worrying about importing `react` whenever you use JSX but don't explicitly use `React`.

**Comment by monsanto** [comment]
I think only if you import it with a temporary name instead of as `React`; you wouldn't want to clobber other imports of the react library. For example, 6to5 automatically did `var React = require('react')` it would mess up applications that do `var React = require('react/addons')` elsewhere in the file.

**Comment by Dashed** [comment]
Agree with @monsanto. I think this is out of scope for 6to5, and should be left for something like webpack/browserify.

But if this feature is in 6to5, I hope I can disable it, because I currently use ProvidePlugin (or externals) in webpack for importing: http://webpack.github.io/docs/list-of-plugins.html#provideplugin

-------

Out of scope, but related, it'd be nice if `React` variable can be aliased to something else (via config), for example: `SomeOtherReact`.

**Comment by sebmck** [comment]
@monsanto That's the only to do it as otherwise you'd be able to do:

```javascript
<a></a>;

React; // you can now access React even though it hasn't been defined
```

@Dashed You'd be able to disable it just like you can disable everything else. See 6to5/6to5#568, nothing is out of scope.

**Comment by tony-kerz** [comment]
i think this would be a valid 'enhancement' to JSX treatment as i'm not a fan of 'magic variables': https://github.com/facebook/react/issues/4110

if you guys agree, can we get this re-opened or is it a rejected enhancement...?

**Comment by sebmck** [comment]
@tony-kerz Nope, this is something that can go into a plugin. In fact, there's already [this](https://github.com/vslinko/babel-plugin-react-require) one that does exactly what you want!

**Comment by jmm** [comment]
If anyone is interested, I created plugin to do the equivalent for the `jsxPragma` option: [babel-plugin-jsx-pragmatic](https://www.npmjs.com/package/babel-plugin-jsx-pragmatic).

**Comment by bloodyowl** [comment]
IIRC react/addons is going to be deprecated in 0.14.0
