### ISSUE TITLE
FR: Browser extensions.

### ISSUE THREAD

**Issue by hemanth** [6to5/6to5#618]
It would be nice to have REPL in browser :)
//cc @sebmck @thejameskyle

**Comment by sebmck** [comment]
What do you mean?

**Comment by hemanth** [comment]
I meant something like [this](https://chrome.google.com/webstore/detail/es6-repl/alploljligeomonipppgaahpkenfnfkn) maybe we can reuse the same or even better convince the author to add 6to5 :)

**Comment by zloirock** [comment]
Something like [this](https://github.com/snookca/CoffeeConsole).

**Comment by sebmck** [comment]
Should probably be done as a community extension instead of something officially supported and maintained.

**Comment by hemanth** [comment]
Makes sense, let see who all can pitch in here and decide :)?

**Comment by sebmck** [comment]
I'm open to creating a repo on the 6to5 org and endorsing it if someone is willing to make and maintain it.

**Comment by hemanth** [comment]
I can! :)

**Comment by sebmck** [comment]
Great! Let me know what you want the repo called and I'll create/add you and whoever wants to help.

**Comment by richgilbank** [comment]
Thanks for the ping :)
I'd be up for adding it as an option or switching it entirely. I imagine the real benefit of using 6to5 in that case would be displaying the output rather than simply executing it, much like the CoffeeConsole, then execution of it would be another option. 
Currently I have it working in Chrome & Opera, so presumably it will also work in Spartan. FF however has a number of outstanding issues currently with the extension SDK, but I'd be happy to jump back into it to see if I can get things running.

**Comment by hemanth** [comment]
`6to5-REPL-Extension` sounds OK? @sebmck 

@richgilbank Awesome!

**Comment by sebmck** [comment]
@hemanth I've created the repo `browser-extension`.

@richgilbank Let me know if you want to collaborate and I'll add you too.

Thanks everyone!

**Comment by hemanth** [comment]
@sebmck Thank you!
