### ISSUE TITLE
`export default class` behaviour in 3.0.0

### ISSUE THREAD

**Issue by FWeinb** [6to5/6to5#621]
We are using 6to5 in [SassDoc](https://github.com/SassDoc/sassdoc/tree/develop) and are happy with it. While trying to upgrade to 3.0.0 we noticed that this:

```js
export default class Name { }
```
is converted to:
```js
"use strict";
var Name = function Name() {};
module.exports = Name;
```
which is fine and expected, we can just do a `let Name = require('./file')` and use the es6 class. 

The curious thing is when adding another `export function test(){}` to the source like:
```js
export default class Name { }
export function test(){}
```
this will now be converted to 
```js
"use strict";
exports.test = test;
var Name = function Name() {};
exports["default"] = Name;
function test() {}
exports.__esModule = true;
```

The  `class Name` is now exported via `exports.default` instead of being the only returned object.

I think this new behaviour was introduced [here](https://github.com/6to5/6to5/commit/8243a34b698db2438283dfb0c9c6e51dfedfe8fd)
 
[Demo](http://6to5.org/repl/#?experimental=true&playground=true&evaluate=false&loose=false&code=export%20default%20class%20Hello%7B%0A%20%20constructor()%20%7B%0A%20%20%20%20console.log(%22Test%22)%3B%0A%20%20%7D%0A%7D%0A%0A%2F%2F%20Uncomment%20this%0A%2F%2F%20export%20var%20test%20%3D%20%7B%7D)

**Comment by sebmck** [comment]
Yeah, this was a 3.0.0 *regression*. When I say regression it's not really. The previous behaviour would pollute the default export and it'd cause all kinds of conflicts. There's no way to replicate having default and named exports in CommonJS so `module.exports` is only set with the `export default` if it's the only export in the file. You can easily get back this functionality by instead of using `export function test(){}` just using `Name.test = function (){};` or even just adding `static test() {}` to the class.

**Comment by FWeinb** [comment]
I though that this could introduce all kinds of conflicts. Thanks for clarifying this.
