### ISSUE TITLE
Istanbul and 6to5/register interop

### ISSUE THREAD

**Issue by sebmck** [6to5/6to5#660]
Detect `process.env.running_in_istanbul` and call the `old` `.js` handler with the compiled code.

**Comment by kolodny** [comment]
This isn't completely working yet, see https://gist.github.com/kolodny/f1e0d34dde7041cd4d02

**Comment by sebmck** [comment]
Fixed as of 3.3.5, thanks!

**Comment by jmeas** [comment]
@sebmck, do you know if it would be possible to author the *tests* themselves in ES6, and have it interop with Istanbul? I've got it working so that the tests can require in ES6 modules, and Istanbul is fine, but when I switch the tests over to ES6 I no longer get coverage.

I know you're super busy, but just a 'yes that is probably possible' or 'no that is not worth your time' would be really helpful to me. The relevant code [is here](https://github.com/babel/6to5-library-boilerplate/blob/master/gulpfile.js#L124-L146).

**Comment by sebmck** [comment]
@jmeas I think istanbul automatically excludes tests from code coverage, at least it does for the babel test coverage, otherwise it should just work. You could try [isparta](https://github.com/douglasduteil/isparta) which I hear makes working with Babel and istanbul a breeze (Disclaimer: I haven't actually used it before).

**Comment by jmeas** [comment]
Ah, yeah, I'm using isparta. I think it has to do with the require hook vs. 6to5's require hook, but I'm not too sure. Thanks for the suggestions!
