### ISSUE TITLE
Spec compatibility: Calling class constructor functions as function should throw

### ISSUE THREAD

**Issue by fkling** [6to5/6to5#682]
This is probably very difficult or impossible to achieve. According to the [newest draft (rev32)](http://wiki.ecmascript.org/doku.php?id=harmony:specification_drafts#february_2_2015_draft_rev_32), calling a `class` constructor function like a normal function (basically everything but calling it with `new` as far as I understand), should throw a `TypeError`:

```js
class Foo {}
Foo(); // should throw
Foo.call({});  // should throw
Foo.apply({});  // should throw
```

The spec uses an internal flag on the function object for that. 

Not sure we can do anything here, just raising awareness and keep track of it.

**Comment by zloirock** [comment]
[Already corrected](http://goo.gl/AznfHO)

**Comment by jeffmo** [comment]
```javascript
class Foo {}
var Foo = class {
  constructor() {
    function Foo() {}
  }
}
Foo.call({});
```

**Comment by fkling** [comment]
Mmh, never mind then :)

**Comment by sebmck** [comment]
Relevant commit 3a11c7d46b5788175c9c1141ff50ed59ce26c40c

**Comment by k1r0s** [comment]
@fkling @kittens so if the specs say 'class instances shouldn't be created by invoking the constructor directly rather than using new keyword'

So what's the deal?!

![image](https://user-images.githubusercontent.com/6052309/33809554-1b0dca38-ddf9-11e7-8293-435f3cdeeba6.png)

Wrapping constructors its not allowed because `there is no way to fulfill the spec than check instanceof`??

**Comment by k1r0s** [comment]
solved by keeping prototype when wrapping ... ¬¬

**Comment by k1r0s** [comment]
This is annoying since wraped function may don't have a reference to the prototype but __returned instance will do!__ and still pass `instanceof` check! 

There is no way to check the correctness of some implementation to assure instances are just created with `new` keyword. I think your workaround isn't correct and unfair

**Comment by nicolo-ribaudo** [comment]
Can you post a code example which throws but shouldn't?

**Comment by k1r0s** [comment]
previous image is

**Comment by nicolo-ribaudo** [comment]
The previous image doesn't contain the class definition, it just shows the error.

**Comment by k1r0s** [comment]
Yes I'm using apply over constructor function.

But I'm not agree about the workaround. TypeScript or V8 harmony impl doesn't complain about constructor wrapping

**Comment by nicolo-ribaudo** [comment]
> Yes I'm using apply over constructor function.

You can't. The only ways of using a funcion defined using `class` are
1. `new yourFunction(...args)`
2. `Reflect.construct(yourFunction, ...args)`


> TypeScript or V8 harmony impl doesn't complain about constructor wrapping

TypeScript isn't 100% spec compliant in diffeent ways, and v8 6.2 throws:

![schermata del 2017-12-11 15-09-56](https://user-images.githubusercontent.com/7000710/33835166-e498eaea-de85-11e7-8b5f-c2a0d03f1bed.png)


> Ecmascript specs just refer to 'creating instances without using new keyword

The specification is very clear about `.apply`ing a class:

- https://tc39.github.io/ecma262/#sec-function.prototype.apply
  ```
  19.2.3.1 Function.prototype.apply ( thisArg, argArray )
    When the apply method is called on an object func with arguments thisArg and
    argArray, the following steps are taken:

    1. If IsCallable(func) is false, throw a TypeError exception.
    ...
    5. Return ? Call(func, thisArg, argList).
  ```

- https://tc39.github.io/ecma262/#sec-call
  ```
  7.3.12 Call ( F, V [ , argumentsList ] )
    The abstract operation Call is used to call the [[Call]] internal method of a
    function object. The operation is called with arguments F, V, and optionally
    argumentsList where F is the function object, V is an ECMAScript language
    value that is the this value of the [[Call]], and argumentsList is the value passed
    to the corresponding argument of the internal method. If argumentsList is not
    present, a new empty List is used as its value. This abstract operation performs
    the following steps:

    1. If argumentsList is not present, set argumentsList to a new empty List.
    2. If IsCallable(F) is false, throw a TypeError exception.
    3. Return ? F.[[Call]](V, argumentsList).
  ```

- https://tc39.github.io/ecma262/#sec-ecmascript-function-objects-call-thisargument-argumentslist
  ```
  9.2.1[[Call]] ( thisArgument, argumentsList )
    The [[Call]] internal method for an ECMAScript function object F is called with
    parameters thisArgument and argumentsList, a List of ECMAScript language
    values. The following steps are taken:

    1. Assert: F is an ECMAScript function object.
    2. If F.[[FunctionKind]] is "classConstructor", throw a TypeError exception.
    ...
  ```

As you can see, if the function is a `classConstructor` it should throw. A feature request for making Babel not spec compliant is very unlikely to be accepted, so I suggest modifying your code to remove that `yourClass.apply()` invocation.

**Comment by k1r0s** [comment]
@nicolo-ribaudo Thanks so much for the detailed response, appreciated. I have to read it in deep.

**Comment by k1r0s** [comment]
BTW im doing something like this:

simple example
```javascript
class Dummy {
  constructor(...arg) {
    oldCtor.apply(this, arg) //babel throws here
  }
}
```
My lib provides ES7 decorators to wrap __methods and constructors__. But for creating instances I always do: `new Dummy` and is completely allowed both TS and V8. Because I'm just using the old Ctor to extend it, but instances are created using `new` from outside..

**Comment by k1r0s** [comment]
https://travis-ci.org/k1r0s/kaop-ts/builds/313761096#L1683
https://github.com/k1r0s/kaop-ts/blob/50e8dd4484bd9d6c77da560cedd8f4c054659d35/test/inject.spec.ts#L41

I have examples where constructors are extended without throwing any err ..

**Comment by nicolo-ribaudo** [comment]
Can you do something like this?

```js
class Dummy extends oldCtor {
  constructor(...args) {
    super(...args);
  }
}
```

**Comment by k1r0s** [comment]
Nope, because it's completely abstracted about how many behaviors will be added to the constructor. Like injection or so (inversion of control)

**Comment by k1r0s** [comment]
Check this. I'm using `apply` but instance doesn't get compromised: 

https://jsbin.com/ciralokohe/edit?js,console

To void the exception to be thrown on my library I just passed prototype reference from old ctor to the new one. But is pointless

**Comment by nicolo-ribaudo** [comment]
> No way, because it's completely abstracted about how many behaviors will be added to the constructor.

If there are many behaviors, will be many classes which extends each other.

You can check this example which shows what I mean: (open your browser's console to see the output)
https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&code_lz=GYVwdgxgLglg9mABDMArAptAggJwOYgC26YUAFAG4CGANiOgJSIDeAUIojulCDkqJFgJEZAMI0qAZ0lM2HDlx59EECdMToAHlBIATSYnFSDc-RwgJJUHCGhwcZAHTOq-GS3Zn5kkAAd0Ds6OrniSADSI1HSMANyeZgC-8YhJHElJrAACKBjY-EQk5ABEABYAnmXolRXotbVFDFk5mFC4BMSkZEUA7nAlVHBwVA2sqsaIACJEhGUe5pbWtlD2ZCEADBHN0Oi6m2gtOwBMsskWYJJwNOiONHB4XcA4cIQqagZnVjZ2OCNmH5fXW73daNP6WAE3O5kLY6XSg-T_K6Q-4wo4MOJpVgZD5QRC6aZlACS5ygVEg6EQAF5EGB0N1JgSuggKSECqQRqNwUigWR8YQZsSrGSIBSUELyXBgAz-WVGqwgA&debug=false&circleciRepo=&evaluate=true&lineWrap=true&presets=stage-0&prettier=false&targets=Node-8.9&version=7.0.0-beta.34

If you want to continue this discussion, please reach me on Slack so that we don't spam with notifications who is whatching this issue/repo. You can ask for an invite at https://github.com/babel/notes/issues/38

**Comment by k1r0s** [comment]
going for slack
