### ISSUE TITLE
source maps & generator breakpoints don't work well together

### ISSUE THREAD

**Issue by simonzack** [6to5/6to5#726]
Breakpoints don't work on the following example in firefox 36:

    function* a(){
      yield 1;
      yield 2;
      yield 3;
    }

    for(let e of a()){
      console.log(e);
    }

On chrome 40 they behave weirdly, when I step over `yield 1` it goes to `yield 3` instead.

**Comment by monsanto** [comment]
I've had a lot of trouble with source maps and breakpoints. I don't often use source maps so I don't know if this is a 6to5 thing or not. If there's evidence it has something to do with 6to5 I can try to track down what my problems were (I disabled source maps a long time ago, so I don't really remember).

**Comment by simonzack** [comment]
The firefox debugger isn't very good, even without source maps it's not able to break, I'll see if I can find out what's causing this.

**Comment by sebmck** [comment]
This is likely [regenerator](https://github.com/facebook/regenerator) destroying location info. I'm not completely familiar with how Firefox would query our built sourcemap so I'm not sure if I can narrow it down any further.

**Comment by simonzack** [comment]
I think [this firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1057031) may have something to do with it, as it doesn't work with or without source maps.

**Comment by sebmck** [comment]
Hmm, possibly. Regardless, I'm confident that this isn't a 6to5 bug. The issue is either in regenerator (unlikely, although very possible) or the Firefox dev tools.

**Comment by appden** [comment]
I haven't looked at this in awhile, but was regenerator definitely the cause of lost source map information last time I checked. I don't think it's fair to close this ticket because users of 6to5 should expect to get proper source map information inside generators, and 6to5's reliance on regenerator is an implementation detail. Instead, I think this should remain open, perhaps referencing a regenerator ticket, until it is fixed.

**Comment by sebmck** [comment]
@appden Feel free to open a regenerator. I'm not willing to support regenerator to this extent, especially after #313.

**Comment by appden** [comment]
@sebmck ok, I'll take a look at this again soon and perhaps file that ticket. #313 was an interesting read!

I personally think 6to5 has outgrown regenerator and could easily tackle a generator transformer using its existing facilities. I'd dare to say that it would be much easier to implement than proper tail calls. :smiley:

Please don't take that as a demand (it's not), but just wanted to share my thoughts. Thank you for all your amazing work on 6to5!

**Comment by sebmck** [comment]
@appden No problem! May revisit in the future to ensure some really tight and solid integration. The goal was initially to do that, clean up regenerator and make it more maintainable with it's 6to5 interaction but #313 left me incredibly unmotivated.

I took a quick look at it and this behaviour is happening in Chrome dev tools too. It's likely that Chrome/Firefox dev tools are trying to resolve the source map column starting at `yield 1;` but since regenerator destroys the `YieldExpression` node and replaces it with it `return 1;` the `ReturnStatement` isn't inheriting location information from `YieldExpression`.
